version: '3.4'

networks: 
  dockersql-network:
    driver: bridge

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI\Dockerfile
    networks:
      - dockersql-network
    depends_on:
      - sql.database
    
  sql.database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "teste@123"
        ACCEPT_EULA: "Y"
    ports: 
      - 1433:1433
    networks:
      - dockersql-network  