version: '3.4'

networks: 
  sampleapinetwork:
    driver: bridge

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI\Dockerfile
    networks: 
      - sampleapinetwork
    depends_on: 
      - "ms-sql-server"

  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "teste@123"
      MSSQL_PID: Express
    ports: 
      - 1433:1433
    networks: 
      - sampleapinetwork

